/**
 * The three authored biomes (Q29), in the order the road walks them.
 *
 * Each is ten stages with its own rhythm: where the elite lands, where you get to
 * breathe, and where the road forks (Q2). Past region three the generator cycles
 * these again at a higher difficulty loop — the map is endless, the authoring is
 * not (`engine/map/generate.ts`).
 */
import type { RegionDef } from '../schemas';

export const REGION_DEFS: readonly RegionDef[] = [
  {
    id: 'region.sunken_isles',
    name: 'Sunken Isles',
    tagline: 'Cold water, colder things under it.',
    themeToken: 'theme-isles',
    stageCount: 10,
    nodePlan: [
      'battle',
      'battle',
      'event',
      'battle',
      'elite',
      'treasure',
      'battle',
      'camp',
      'battle',
      'boss',
    ],
    fork: {
      startIndex: 6,
      length: 3,
      risky: ['elite', 'battle', 'battle'],
      riskyRewardBonusPercent: 30,
    },
    nameTable: [
      'Shallow Reach',
      'Coral Keep',
      'Salt Flats',
      'Drowned Pier',
      'Kelp Maze',
      'Screaming Tomb',
      'Under Ice',
      'Pirate Ship',
      'Far Island',
      'Tyrant Deep',
    ],
    enemyPool: [
      'enemy.shore_scavengers',
      'enemy.tidepool_pack',
      'enemy.reef_ambush',
      'enemy.wraith_tide',
      'enemy.salt_circle',
      'enemy.deep_hunger',
      'enemy.drowned_vanguard',
      'enemy.black_current',
    ],
    elitePool: ['enemy.frozen_vigil', 'enemy.deep_court'],
    bossPool: ['enemy.tide_tyrant'],
    eventPool: [
      'encounter.wrecked_caravan',
      'encounter.collapsed_bridge',
      'encounter.buried_cache',
      'encounter.drowned_hoard',
      'encounter.roadside_camp',
      'encounter.old_watchtower',
    ],
    modifierPool: [
      'modifier.ironhide',
      'modifier.quickened',
      'modifier.endless_tide',
      'modifier.choking_dust',
      'modifier.blessed_ground',
    ],
    lootTable: 'loot.isles_battle',
    bossLootTable: 'loot.isles_boss',
    elementBias: 'ice',
    difficultyScale: 1,
    chestThresholds: [8, 16, 22],
    chestLootTable: 'loot.chest_isles',
  },
  {
    id: 'region.ashfall_reach',
    name: 'Ashfall Reach',
    tagline: 'The mountain is still awake.',
    themeToken: 'theme-ashfall',
    stageCount: 10,
    nodePlan: [
      'battle',
      'event',
      'battle',
      'battle',
      'elite',
      'battle',
      'treasure',
      'battle',
      'camp',
      'boss',
    ],
    fork: {
      startIndex: 6,
      length: 3,
      risky: ['elite', 'battle', 'elite'],
      riskyRewardBonusPercent: 35,
    },
    nameTable: [
      'Cinder Road',
      'Black Glass',
      'Slag Yards',
      'The Bellows',
      'Ashfall',
      'Broken Crucible',
      'Emberwatch',
      'Smoking Stair',
      'Furnace Gate',
      'Vashk’s Seat',
    ],
    enemyPool: [
      'enemy.cinder_pack',
      'enemy.ashfall_scouts',
      'enemy.magma_line',
      'enemy.pyre_choir',
      'enemy.forge_watch',
      'enemy.emberfall',
      'enemy.slag_vanguard',
      'enemy.the_furnace',
    ],
    elitePool: ['enemy.reaver_hunt', 'enemy.crucible_guard'],
    bossPool: ['enemy.emberlord_court'],
    eventPool: [
      'encounter.old_shrine',
      'encounter.wrecked_caravan',
      'encounter.sealed_strongbox',
      'encounter.tribute_pile',
      'encounter.hot_spring',
      'encounter.roadside_camp',
    ],
    modifierPool: [
      'modifier.frenzied',
      'modifier.scorched',
      'modifier.ironhide',
      'modifier.quickened',
      'modifier.endless_tide',
    ],
    lootTable: 'loot.ashfall_battle',
    bossLootTable: 'loot.ashfall_boss',
    elementBias: 'fire',
    difficultyScale: 1.08,
    chestThresholds: [8, 16, 22],
    chestLootTable: 'loot.chest_ashfall',
  },
  {
    id: 'region.verdant_wound',
    name: 'Verdant Wound',
    tagline: 'Everything here is growing wrong.',
    themeToken: 'theme-verdant',
    stageCount: 10,
    nodePlan: [
      'battle',
      'battle',
      'camp',
      'battle',
      'elite',
      'event',
      'battle',
      'treasure',
      'battle',
      'boss',
    ],
    fork: {
      startIndex: 3,
      length: 2,
      risky: ['elite', 'battle'],
      riskyRewardBonusPercent: 30,
    },
    nameTable: [
      'Green Threshold',
      'Choking Path',
      'Spore Hollow',
      'Bramble Gate',
      'The Overgrowth',
      'Rot Grove',
      'Hanging Roots',
      'Quiet Ring',
      'Split Trunk',
      'The Rootmother',
    ],
    enemyPool: [
      'enemy.thorn_pack',
      'enemy.spore_drift',
      'enemy.bramble_wall',
      'enemy.moss_circle',
      'enemy.creeping_dark',
      'enemy.rot_grove',
      'enemy.blight_hunt',
      'enemy.the_wound',
    ],
    elitePool: ['enemy.fangs_of_the_grove', 'enemy.deep_roots'],
    bossPool: ['enemy.rootmother_hollow'],
    eventPool: [
      'encounter.wandering_scholar',
      'encounter.collapsed_bridge',
      'encounter.buried_cache',
      'encounter.tribute_pile',
      'encounter.quiet_grove',
      'encounter.hot_spring',
    ],
    modifierPool: [
      'modifier.blessed_ground',
      'modifier.endless_tide',
      'modifier.choking_dust',
      'modifier.frenzied',
      'modifier.ironhide',
    ],
    lootTable: 'loot.verdant_battle',
    bossLootTable: 'loot.verdant_boss',
    elementBias: 'nature',
    difficultyScale: 1.16,
    chestThresholds: [8, 16, 22],
    chestLootTable: 'loot.chest_verdant',
  },
];
