/**
 * Slice roster.
 *
 * Every card points `artKey` at its own id; all of them currently resolve to the
 * one shared placeholder avatar, and the owner's final per-card art drops in later
 * with no data change (CLAUDE.md rule 6).
 *
 * Balance shape: Strength (max HP) is the big battlefield number and scales roughly
 * 5-8x Attack, so fights last several rounds instead of trading one-shots. Ranged
 * cards trade Strength for reach; melee cards are tankier because the front row
 * absorbs first (Q7).
 */
import type { CardDef } from '../schemas';

const PLAYER_UNITS: readonly CardDef[] = [
  {
    id: 'card.thorn_sprout',
    name: 'Thorn Sprout',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 340, attack: 46, speed: 10 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.venom_bite', unlockStars: 1 },
      { skillId: 'skill.spore_burst', unlockStars: 2 },
      { skillId: 'skill.bulwark_call', unlockStars: 3 },
      { skillId: 'skill.second_wind', unlockStars: 4 },
      { skillId: 'skill.rally_cry', unlockStars: 5 },
    ],
    artKey: 'card.thorn_sprout',
    lore: 'Grown from a seed that refused to stop growing.',
    enemyOnly: false,
  },
  {
    id: 'card.spark_wisp',
    name: 'Spark Wisp',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'ranged',
    element: 'lightning',
    baseStats: { strength: 240, attack: 58, speed: 14 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.thunder_clap', unlockStars: 1 },
      { skillId: 'skill.chill_wind', unlockStars: 2 },
      { skillId: 'skill.frost_lance', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.spark_wisp',
    lore: 'A stray charge that never found its cloud.',
    enemyOnly: false,
  },
  {
    id: 'card.stone_sentry',
    name: 'Stone Sentry',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 520, attack: 42, speed: 7 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.guard_stance', unlockStars: 1 },
      { skillId: 'skill.bulwark_call', unlockStars: 2 },
      { skillId: 'skill.rally_cry', unlockStars: 3 },
      { skillId: 'skill.second_wind', unlockStars: 4 },
      { skillId: 'skill.thunder_clap', unlockStars: 5 },
    ],
    artKey: 'card.stone_sentry',
    lore: 'Older than the road it guards.',
    enemyOnly: false,
  },
  {
    id: 'card.frost_imp',
    name: 'Frost Imp',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'ranged',
    element: 'ice',
    baseStats: { strength: 290, attack: 64, speed: 12 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.frost_lance', unlockStars: 1 },
      { skillId: 'skill.chill_wind', unlockStars: 2 },
      { skillId: 'skill.thunder_clap', unlockStars: 3 },
      { skillId: 'skill.spore_burst', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.frost_imp',
    lore: 'Delighted by the sound of chattering teeth.',
    enemyOnly: false,
  },
  {
    id: 'card.bog_lurker',
    name: 'Bog Lurker',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 470, attack: 50, speed: 9 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.splash',
    skills: [
      { skillId: 'skill.venom_bite', unlockStars: 1 },
      { skillId: 'skill.spore_burst', unlockStars: 2 },
      { skillId: 'skill.riptide_slash', unlockStars: 3 },
      { skillId: 'skill.bulwark_call', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.bog_lurker',
    lore: 'Patient, damp, and entirely without mercy.',
    enemyOnly: false,
  },
  {
    id: 'card.ember_drake',
    name: 'Ember Drake',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 560, attack: 78, speed: 11 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.cinder_volley', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
      { skillId: 'skill.bulwark_call', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.ember_drake',
    lore: 'Hatched angry. Stayed that way.',
    enemyOnly: false,
  },
  {
    id: 'card.gale_archer',
    name: 'Gale Archer',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'ranged',
    element: 'nature',
    baseStats: { strength: 380, attack: 92, speed: 15 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.rally_cry', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
      { skillId: 'skill.chill_wind', unlockStars: 3 },
      { skillId: 'skill.thunder_clap', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.gale_archer',
    lore: 'Never misses. Rarely explains how.',
    enemyOnly: false,
  },
  {
    id: 'card.cinder_hound',
    name: 'Cinder Hound',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 500, attack: 88, speed: 16 },
    growth: 'growth.rare',
    attackPattern: 'pattern.cross',
    skills: [
      { skillId: 'skill.cinder_volley', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
      { skillId: 'skill.thunder_clap', unlockStars: 3 },
      { skillId: 'skill.chill_wind', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.cinder_hound',
    lore: 'Leaves scorched pawprints wherever it hunts.',
    enemyOnly: false,
  },
  {
    id: 'card.glacier_warden',
    name: 'Glacier Warden',
    cardClass: 'unit',
    rarity: 'epic',
    attackType: 'melee',
    element: 'ice',
    baseStats: { strength: 820, attack: 92, speed: 9 },
    growth: 'growth.epic',
    attackPattern: 'pattern.splash',
    skills: [
      { skillId: 'skill.guard_stance', unlockStars: 1 },
      { skillId: 'skill.bulwark_call', unlockStars: 2 },
      { skillId: 'skill.frost_lance', unlockStars: 3 },
      { skillId: 'skill.chill_wind', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.glacier_warden',
    lore: 'Stands where the ice ends and refuses to move.',
    enemyOnly: false,
  },
  {
    id: 'card.stormcaller_nix',
    name: 'Stormcaller Nix',
    cardClass: 'unit',
    rarity: 'epic',
    attackType: 'ranged',
    element: 'lightning',
    baseStats: { strength: 470, attack: 118, speed: 15 },
    growth: 'growth.epic',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.thunder_clap', unlockStars: 1 },
      { skillId: 'skill.chill_wind', unlockStars: 2 },
      { skillId: 'skill.riptide_slash', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.stormcaller_nix',
    lore: 'Counts the seconds between flash and thunder, then halves them.',
    enemyOnly: false,
  },
  {
    id: 'card.sunken_king',
    name: 'Sunken King',
    cardClass: 'unit',
    rarity: 'legendary',
    attackType: 'melee',
    element: 'dark',
    baseStats: { strength: 1120, attack: 132, speed: 12 },
    growth: 'growth.legendary',
    attackPattern: 'pattern.row',
    skills: [
      { skillId: 'skill.tide_surge', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
      { skillId: 'skill.bulwark_call', unlockStars: 3 },
      { skillId: 'skill.chill_wind', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.sunken_king',
    lore: 'Ruled these waters before they were water.',
    enemyOnly: false,
  },
];

/**
 * Heroes (Q12): one per deck. They fight on the board AND carry a passive leader
 * skill that buffs the whole deck — the reference's "Buffs all other Melee allies
 * by 12% of this card's max Strength" pattern.
 */
const PLAYER_HEROES: readonly CardDef[] = [
  {
    id: 'card.captain_marrow',
    name: 'Captain Marrow',
    cardClass: 'hero',
    rarity: 'epic',
    attackType: 'melee',
    element: 'dark',
    baseStats: { strength: 720, attack: 84, speed: 12 },
    growth: 'growth.epic',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.rally_cry', unlockStars: 1 },
      { skillId: 'skill.bulwark_call', unlockStars: 2 },
      { skillId: 'skill.riptide_slash', unlockStars: 3 },
      { skillId: 'skill.guard_stance', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    leaderSkill: {
      description: 'Buffs all other Melee allies by 12% Strength.',
      target: { side: 'ally', scope: 'all', where: { attackType: 'melee' } },
      stat: 'strength',
      percent: 12,
    },
    artKey: 'card.captain_marrow',
    lore: 'Lost the ship. Kept the crew.',
    enemyOnly: false,
  },
  {
    id: 'card.oracle_vess',
    name: 'Oracle Vess',
    cardClass: 'hero',
    rarity: 'epic',
    attackType: 'ranged',
    element: 'ice',
    baseStats: { strength: 540, attack: 96, speed: 14 },
    growth: 'growth.epic',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.mend_spore', unlockStars: 1 },
      { skillId: 'skill.frost_lance', unlockStars: 2 },
      { skillId: 'skill.chill_wind', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    leaderSkill: {
      description: 'Buffs all other Ranged allies by 10% Attack.',
      target: { side: 'ally', scope: 'all', where: { attackType: 'ranged' } },
      stat: 'attack',
      percent: 10,
    },
    artKey: 'card.oracle_vess',
    lore: 'Reads the tide the way others read a page.',
    enemyOnly: false,
  },
  {
    id: 'card.warden_ashvale',
    name: 'Warden Ashvale',
    cardClass: 'hero',
    rarity: 'legendary',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 1040, attack: 126, speed: 13 },
    growth: 'growth.legendary',
    attackPattern: 'pattern.cross',
    skills: [
      { skillId: 'skill.riptide_slash', unlockStars: 1 },
      { skillId: 'skill.cinder_volley', unlockStars: 2 },
      { skillId: 'skill.bulwark_call', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    leaderSkill: {
      description: 'Buffs all other allies by 8% Attack.',
      target: { side: 'ally', scope: 'all' },
      stat: 'attack',
      percent: 8,
    },
    artKey: 'card.warden_ashvale',
    lore: 'Held the last bridge alone, and is still holding it.',
    enemyOnly: false,
  },
];

/** Enemy-only cards. The registry refuses to put these in summon pools. */
const ENEMIES: readonly CardDef[] = [
  {
    id: 'card.gloom_rat',
    name: 'Gloom Rat',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'melee',
    element: 'dark',
    baseStats: { strength: 260, attack: 40, speed: 12 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [],
    artKey: 'card.gloom_rat',
    enemyOnly: true,
  },
  {
    id: 'card.gloom_bat',
    name: 'Gloom Bat',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'ranged',
    element: 'dark',
    baseStats: { strength: 200, attack: 48, speed: 15 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [],
    artKey: 'card.gloom_bat',
    enemyOnly: true,
  },
  {
    id: 'card.brine_crab',
    name: 'Brine Crab',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'melee',
    element: 'ice',
    baseStats: { strength: 430, attack: 44, speed: 6 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.guard_stance', unlockStars: 1 },
      { skillId: 'skill.bulwark_call', unlockStars: 2 },
    ],
    artKey: 'card.brine_crab',
    enemyOnly: true,
  },
  {
    id: 'card.reef_stalker',
    name: 'Reef Stalker',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'ranged',
    element: 'nature',
    baseStats: { strength: 250, attack: 62, speed: 13 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.venom_bite', unlockStars: 1 },
      { skillId: 'skill.spore_burst', unlockStars: 2 },
    ],
    artKey: 'card.reef_stalker',
    enemyOnly: true,
  },
  {
    id: 'card.tide_wraith',
    name: 'Tide Wraith',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'ranged',
    element: 'ice',
    baseStats: { strength: 330, attack: 76, speed: 12 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.frost_lance', unlockStars: 1 },
      { skillId: 'skill.chill_wind', unlockStars: 2 },
    ],
    artKey: 'card.tide_wraith',
    enemyOnly: true,
  },
  {
    id: 'card.coral_brute',
    name: 'Coral Brute',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 620, attack: 70, speed: 8 },
    growth: 'growth.rare',
    attackPattern: 'pattern.splash',
    skills: [],
    artKey: 'card.coral_brute',
    enemyOnly: true,
  },
  {
    id: 'card.salt_shaman',
    name: 'Salt Shaman',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'ranged',
    element: 'lightning',
    baseStats: { strength: 340, attack: 68, speed: 11 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.mend_spore', unlockStars: 1 },
      { skillId: 'skill.rally_cry', unlockStars: 2 },
    ],
    artKey: 'card.salt_shaman',
    enemyOnly: true,
  },
  {
    id: 'card.deep_maw',
    name: 'Deep Maw',
    cardClass: 'unit',
    rarity: 'epic',
    attackType: 'melee',
    element: 'dark',
    baseStats: { strength: 780, attack: 86, speed: 9 },
    growth: 'growth.epic',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.venom_bite', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
    ],
    artKey: 'card.deep_maw',
    enemyOnly: true,
  },
  {
    id: 'card.tide_tyrant',
    name: 'Tide Tyrant',
    cardClass: 'unit',
    rarity: 'legendary',
    attackType: 'melee',
    element: 'ice',
    baseStats: { strength: 1900, attack: 104, speed: 10 },
    growth: 'growth.legendary',
    attackPattern: 'pattern.row',
    skills: [
      { skillId: 'skill.tide_surge', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
      { skillId: 'skill.chill_wind', unlockStars: 3 },
    ],
    artKey: 'card.tide_tyrant',
    lore: 'The isles were quiet before it woke.',
    enemyOnly: true,
  },
];

export const CARD_DEFS: readonly CardDef[] = [...PLAYER_UNITS, ...PLAYER_HEROES, ...ENEMIES];

/** The deck the player starts with — a hero plus a workable spread of roles. */
export const STARTER_CARD_IDS: readonly string[] = [
  'card.captain_marrow',
  'card.ember_drake',
  'card.stone_sentry',
  'card.thorn_sprout',
  'card.gale_archer',
  'card.frost_imp',
  'card.spark_wisp',
];
