/**
 * Slice roster.
 *
 * Every card points `artKey` at its own id; all of them currently resolve to the
 * one shared placeholder avatar, and the owner's final per-card art drops in later
 * with no data change (CLAUDE.md rule 6).
 *
 * Balance shape: Strength (max HP) is the big battlefield number and scales roughly
 * 5-8x Attack, so fights last several rounds instead of trading one-shots. Ranged
 * cards trade Strength for reach; melee cards are tankier because the front row
 * absorbs first (Q7).
 */
import type { CardDef } from '../schemas';

const PLAYER_UNITS: readonly CardDef[] = [
  {
    id: 'card.thorn_sprout',
    name: 'Thorn Sprout',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 340, attack: 46, speed: 10 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.venom_bite', unlockStars: 1 },
      { skillId: 'skill.spore_burst', unlockStars: 2 },
      { skillId: 'skill.bulwark_call', unlockStars: 3 },
      { skillId: 'skill.second_wind', unlockStars: 4 },
      { skillId: 'skill.rally_cry', unlockStars: 5 },
    ],
    artKey: 'card.thorn_sprout',
    lore: 'Grown from a seed that refused to stop growing.',
    enemyOnly: false,
  },
  {
    id: 'card.spark_wisp',
    name: 'Spark Wisp',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'ranged',
    element: 'lightning',
    baseStats: { strength: 240, attack: 58, speed: 14 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.thunder_clap', unlockStars: 1 },
      { skillId: 'skill.chill_wind', unlockStars: 2 },
      { skillId: 'skill.frost_lance', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.spark_wisp',
    lore: 'A stray charge that never found its cloud.',
    enemyOnly: false,
  },
  {
    id: 'card.stone_sentry',
    name: 'Stone Sentry',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 520, attack: 42, speed: 7 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.guard_stance', unlockStars: 1 },
      { skillId: 'skill.bulwark_call', unlockStars: 2 },
      { skillId: 'skill.rally_cry', unlockStars: 3 },
      { skillId: 'skill.second_wind', unlockStars: 4 },
      { skillId: 'skill.thunder_clap', unlockStars: 5 },
    ],
    artKey: 'card.stone_sentry',
    lore: 'Older than the road it guards.',
    enemyOnly: false,
  },
  {
    id: 'card.frost_imp',
    name: 'Frost Imp',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'ranged',
    element: 'ice',
    baseStats: { strength: 290, attack: 64, speed: 12 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.frost_lance', unlockStars: 1 },
      { skillId: 'skill.chill_wind', unlockStars: 2 },
      { skillId: 'skill.thunder_clap', unlockStars: 3 },
      { skillId: 'skill.spore_burst', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.frost_imp',
    lore: 'Delighted by the sound of chattering teeth.',
    enemyOnly: false,
  },
  {
    id: 'card.bog_lurker',
    name: 'Bog Lurker',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 470, attack: 50, speed: 9 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.splash',
    skills: [
      { skillId: 'skill.venom_bite', unlockStars: 1 },
      { skillId: 'skill.spore_burst', unlockStars: 2 },
      { skillId: 'skill.riptide_slash', unlockStars: 3 },
      { skillId: 'skill.bulwark_call', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.bog_lurker',
    lore: 'Patient, damp, and entirely without mercy.',
    enemyOnly: false,
  },
  {
    id: 'card.ember_drake',
    name: 'Ember Drake',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 560, attack: 78, speed: 11 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.cinder_volley', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
      { skillId: 'skill.bulwark_call', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.ember_drake',
    lore: 'Hatched angry. Stayed that way.',
    enemyOnly: false,
  },
  {
    id: 'card.gale_archer',
    name: 'Gale Archer',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'ranged',
    element: 'nature',
    baseStats: { strength: 380, attack: 92, speed: 15 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.rally_cry', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
      { skillId: 'skill.chill_wind', unlockStars: 3 },
      { skillId: 'skill.thunder_clap', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.gale_archer',
    lore: 'Never misses. Rarely explains how.',
    enemyOnly: false,
  },
  {
    id: 'card.cinder_hound',
    name: 'Cinder Hound',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 500, attack: 88, speed: 16 },
    growth: 'growth.rare',
    attackPattern: 'pattern.cross',
    skills: [
      { skillId: 'skill.cinder_volley', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
      { skillId: 'skill.thunder_clap', unlockStars: 3 },
      { skillId: 'skill.chill_wind', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.cinder_hound',
    lore: 'Leaves scorched pawprints wherever it hunts.',
    enemyOnly: false,
  },
  {
    id: 'card.glacier_warden',
    name: 'Glacier Warden',
    cardClass: 'unit',
    rarity: 'epic',
    attackType: 'melee',
    element: 'ice',
    baseStats: { strength: 820, attack: 92, speed: 9 },
    growth: 'growth.epic',
    attackPattern: 'pattern.splash',
    skills: [
      { skillId: 'skill.guard_stance', unlockStars: 1 },
      { skillId: 'skill.bulwark_call', unlockStars: 2 },
      { skillId: 'skill.frost_lance', unlockStars: 3 },
      { skillId: 'skill.chill_wind', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.glacier_warden',
    lore: 'Stands where the ice ends and refuses to move.',
    enemyOnly: false,
  },
  {
    id: 'card.stormcaller_nix',
    name: 'Stormcaller Nix',
    cardClass: 'unit',
    rarity: 'epic',
    attackType: 'ranged',
    element: 'lightning',
    baseStats: { strength: 470, attack: 118, speed: 15 },
    growth: 'growth.epic',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.thunder_clap', unlockStars: 1 },
      { skillId: 'skill.chill_wind', unlockStars: 2 },
      { skillId: 'skill.riptide_slash', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.stormcaller_nix',
    lore: 'Counts the seconds between flash and thunder, then halves them.',
    enemyOnly: false,
  },
  {
    id: 'card.sunken_king',
    name: 'Sunken King',
    cardClass: 'unit',
    rarity: 'legendary',
    attackType: 'melee',
    element: 'dark',
    baseStats: { strength: 1120, attack: 132, speed: 12 },
    growth: 'growth.legendary',
    attackPattern: 'pattern.row',
    skills: [
      { skillId: 'skill.tide_surge', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
      { skillId: 'skill.bulwark_call', unlockStars: 3 },
      { skillId: 'skill.chill_wind', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.sunken_king',
    lore: 'Ruled these waters before they were water.',
    enemyOnly: false,
  },

  // --- Phase 7: breadth to the first-release target (Q29) --------------------
  {
    id: 'card.dust_moth',
    name: 'Dust Moth',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'ranged',
    element: 'nature',
    baseStats: { strength: 225, attack: 55, speed: 16 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.spore_burst', unlockStars: 1 },
      { skillId: 'skill.venom_bite', unlockStars: 2 },
      { skillId: 'skill.gale_step', unlockStars: 3 },
      { skillId: 'skill.mend_spore', unlockStars: 4 },
      { skillId: 'skill.blight_bloom', unlockStars: 5 },
    ],
    artKey: 'card.dust_moth',
    lore: 'Draws a line of powder wherever it goes.',
    enemyOnly: false,
  },
  {
    id: 'card.pebble_kin',
    name: 'Pebble Kin',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 365, attack: 43, speed: 8 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.guard_stance', unlockStars: 1 },
      { skillId: 'skill.stone_skin', unlockStars: 2 },
      { skillId: 'skill.iron_vow', unlockStars: 3 },
      { skillId: 'skill.bulwark_call', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.pebble_kin',
    lore: 'Small, patient, and much heavier than it looks.',
    enemyOnly: false,
  },
  {
    id: 'card.candle_imp',
    name: 'Candle Imp',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 300, attack: 51, speed: 13 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.searing_lash', unlockStars: 1 },
      { skillId: 'skill.cinder_volley', unlockStars: 2 },
      { skillId: 'skill.iron_vow', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.candle_imp',
    lore: 'Burns down faster the harder it fights.',
    enemyOnly: false,
  },
  {
    id: 'card.brook_sprite',
    name: 'Brook Sprite',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'ranged',
    element: 'ice',
    baseStats: { strength: 235, attack: 56, speed: 15 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.chill_wind', unlockStars: 1 },
      { skillId: 'skill.frost_lance', unlockStars: 2 },
      { skillId: 'skill.warding_hymn', unlockStars: 3 },
      { skillId: 'skill.mend_spore', unlockStars: 4 },
      { skillId: 'skill.avalanche', unlockStars: 5 },
    ],
    artKey: 'card.brook_sprite',
    lore: 'Left a stream somewhere and has not found it since.',
    enemyOnly: false,
  },
  {
    id: 'card.grave_moth',
    name: 'Grave Moth',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'ranged',
    element: 'dark',
    baseStats: { strength: 240, attack: 58, speed: 14 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.hollow_grasp', unlockStars: 1 },
      { skillId: 'skill.venom_bite', unlockStars: 2 },
      { skillId: 'skill.blight_bloom', unlockStars: 3 },
      { skillId: 'skill.chill_wind', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.grave_moth',
    lore: 'Feeds on what other things leave behind.',
    enemyOnly: false,
  },
  {
    id: 'card.ash_pup',
    name: 'Ash Pup',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 320, attack: 49, speed: 15 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.searing_lash', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
      { skillId: 'skill.rally_cry', unlockStars: 3 },
      { skillId: 'skill.guard_stance', unlockStars: 4 },
      { skillId: 'skill.gale_step', unlockStars: 5 },
    ],
    artKey: 'card.ash_pup',
    lore: 'Warm to the touch. Warmer if it likes you.',
    enemyOnly: false,
  },
  {
    id: 'card.tidecaller',
    name: 'Tidecaller',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'ranged',
    element: 'ice',
    baseStats: { strength: 330, attack: 68, speed: 12 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.tide_surge', unlockStars: 1 },
      { skillId: 'skill.frost_lance', unlockStars: 2 },
      { skillId: 'skill.warding_hymn', unlockStars: 3 },
      { skillId: 'skill.avalanche', unlockStars: 4 },
      { skillId: 'skill.last_light', unlockStars: 5 },
    ],
    artKey: 'card.tidecaller',
    lore: 'Asks the water for a favour and usually gets one.',
    enemyOnly: false,
  },
  {
    id: 'card.emberling',
    name: 'Emberling',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 470, attack: 60, speed: 11 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.cinder_volley', unlockStars: 1 },
      { skillId: 'skill.searing_lash', unlockStars: 2 },
      { skillId: 'skill.iron_vow', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.emberling',
    lore: 'Every scar on it is a smaller fire it walked out of.',
    enemyOnly: false,
  },
  {
    id: 'card.mireback',
    name: 'Mireback',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 530, attack: 55, speed: 7 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.guard_stance', unlockStars: 1 },
      { skillId: 'skill.stone_skin', unlockStars: 2 },
      { skillId: 'skill.venom_bite', unlockStars: 3 },
      { skillId: 'skill.iron_vow', unlockStars: 4 },
      { skillId: 'skill.bulwark_call', unlockStars: 5 },
    ],
    artKey: 'card.mireback',
    lore: 'Carries half the swamp on its shoulders, deliberately.',
    enemyOnly: false,
  },
  {
    id: 'card.storm_kite',
    name: 'Storm Kite',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'ranged',
    element: 'lightning',
    baseStats: { strength: 300, attack: 74, speed: 18 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.thunder_clap', unlockStars: 1 },
      { skillId: 'skill.static_field', unlockStars: 2 },
      { skillId: 'skill.gale_step', unlockStars: 3 },
      { skillId: 'skill.chill_wind', unlockStars: 4 },
      { skillId: 'skill.last_light', unlockStars: 5 },
    ],
    artKey: 'card.storm_kite',
    lore: 'Rides the front of the weather rather than under it.',
    enemyOnly: false,
  },
  {
    id: 'card.dusk_warden',
    name: 'Dusk Warden',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'melee',
    element: 'dark',
    baseStats: { strength: 490, attack: 62, speed: 10 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.hollow_grasp', unlockStars: 1 },
      { skillId: 'skill.iron_vow', unlockStars: 2 },
      { skillId: 'skill.guard_stance', unlockStars: 3 },
      { skillId: 'skill.blight_bloom', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    artKey: 'card.dusk_warden',
    lore: 'Keeps the last watch, the one nobody volunteers for.',
    enemyOnly: false,
  },
  {
    id: 'card.frostbind_saint',
    name: 'Frostbind Saint',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'ranged',
    element: 'ice',
    baseStats: { strength: 430, attack: 86, speed: 13 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.frost_lance', unlockStars: 1 },
      { skillId: 'skill.avalanche', unlockStars: 2 },
      { skillId: 'skill.warding_hymn', unlockStars: 3 },
      { skillId: 'skill.last_light', unlockStars: 4 },
      { skillId: 'skill.chill_wind', unlockStars: 5 },
    ],
    artKey: 'card.frostbind_saint',
    lore: 'Freezes the wound shut and calls that mercy.',
    enemyOnly: false,
  },
  {
    id: 'card.thunder_ram',
    name: 'Thunder Ram',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'melee',
    element: 'lightning',
    baseStats: { strength: 660, attack: 78, speed: 11 },
    growth: 'growth.rare',
    attackPattern: 'pattern.splash',
    skills: [
      { skillId: 'skill.thunder_clap', unlockStars: 1 },
      { skillId: 'skill.static_field', unlockStars: 2 },
      { skillId: 'skill.iron_vow', unlockStars: 3 },
      { skillId: 'skill.stone_skin', unlockStars: 4 },
      { skillId: 'skill.rally_cry', unlockStars: 5 },
    ],
    artKey: 'card.thunder_ram',
    lore: 'Hits like weather and takes it about as personally.',
    enemyOnly: false,
  },
  {
    id: 'card.rootspeaker',
    name: 'Rootspeaker',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'ranged',
    element: 'nature',
    baseStats: { strength: 450, attack: 80, speed: 12 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.blight_bloom', unlockStars: 1 },
      { skillId: 'skill.mend_spore', unlockStars: 2 },
      { skillId: 'skill.spore_burst', unlockStars: 3 },
      { skillId: 'skill.last_light', unlockStars: 4 },
      { skillId: 'skill.warding_hymn', unlockStars: 5 },
    ],
    artKey: 'card.rootspeaker',
    lore: 'The forest answers. It just takes its time about it.',
    enemyOnly: false,
  },
  {
    id: 'card.pyre_knight',
    name: 'Pyre Knight',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 700, attack: 82, speed: 10 },
    growth: 'growth.rare',
    attackPattern: 'pattern.row',
    skills: [
      { skillId: 'skill.searing_lash', unlockStars: 1 },
      { skillId: 'skill.iron_vow', unlockStars: 2 },
      { skillId: 'skill.cinder_volley', unlockStars: 3 },
      { skillId: 'skill.bulwark_call', unlockStars: 4 },
      { skillId: 'skill.rally_cry', unlockStars: 5 },
    ],
    artKey: 'card.pyre_knight',
    lore: 'Sworn to a fire that has not gone out in nine hundred years.',
    enemyOnly: false,
  },
  {
    id: 'card.aurora_seer',
    name: 'Aurora Seer',
    cardClass: 'unit',
    rarity: 'epic',
    attackType: 'ranged',
    element: 'ice',
    baseStats: { strength: 640, attack: 112, speed: 15 },
    growth: 'growth.epic',
    attackPattern: 'pattern.column',
    skills: [
      { skillId: 'skill.avalanche', unlockStars: 1 },
      { skillId: 'skill.frost_lance', unlockStars: 2 },
      { skillId: 'skill.warding_hymn', unlockStars: 3 },
      { skillId: 'skill.last_light', unlockStars: 4 },
      { skillId: 'skill.gale_step', unlockStars: 5 },
    ],
    artKey: 'card.aurora_seer',
    lore: 'Reads the lights and does not always like the reading.',
    enemyOnly: false,
  },
  {
    id: 'card.grove_tyrant',
    name: 'Grove Tyrant',
    cardClass: 'unit',
    rarity: 'epic',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 900, attack: 104, speed: 9 },
    growth: 'growth.epic',
    attackPattern: 'pattern.splash',
    skills: [
      { skillId: 'skill.blight_bloom', unlockStars: 1 },
      { skillId: 'skill.iron_vow', unlockStars: 2 },
      { skillId: 'skill.stone_skin', unlockStars: 3 },
      { skillId: 'skill.venom_bite', unlockStars: 4 },
      { skillId: 'skill.bulwark_call', unlockStars: 5 },
    ],
    artKey: 'card.grove_tyrant',
    lore: 'The old growth decided it had opinions.',
    enemyOnly: false,
  },
  {
    id: 'card.cinderwake',
    name: 'Cinderwake',
    cardClass: 'unit',
    rarity: 'epic',
    attackType: 'ranged',
    element: 'fire',
    baseStats: { strength: 690, attack: 118, speed: 16 },
    growth: 'growth.epic',
    attackPattern: 'pattern.row',
    skills: [
      { skillId: 'skill.cinder_volley', unlockStars: 1 },
      { skillId: 'skill.searing_lash', unlockStars: 2 },
      { skillId: 'skill.static_field', unlockStars: 3 },
      { skillId: 'skill.gale_step', unlockStars: 4 },
      { skillId: 'skill.last_light', unlockStars: 5 },
    ],
    artKey: 'card.cinderwake',
    lore: 'Leaves a trail of small fires that are somehow all the same fire.',
    enemyOnly: false,
  },
  {
    id: 'card.storm_sovereign',
    name: 'Storm Sovereign',
    cardClass: 'unit',
    rarity: 'legendary',
    attackType: 'melee',
    element: 'lightning',
    baseStats: { strength: 1250, attack: 136, speed: 14 },
    growth: 'growth.legendary',
    attackPattern: 'pattern.cross',
    skills: [
      { skillId: 'skill.static_field', unlockStars: 1 },
      { skillId: 'skill.thunder_clap', unlockStars: 2 },
      { skillId: 'skill.gale_step', unlockStars: 3 },
      { skillId: 'skill.iron_vow', unlockStars: 4 },
      { skillId: 'skill.last_light', unlockStars: 5 },
    ],
    artKey: 'card.storm_sovereign',
    lore: 'The sky does not lend its power. It follows him.',
    enemyOnly: false,
  },
];

/**
 * Heroes (Q12): one per deck. They fight on the board AND carry a passive leader
 * skill that buffs the whole deck — the reference's "Buffs all other Melee allies
 * by 12% of this card's max Strength" pattern.
 */
const PLAYER_HEROES: readonly CardDef[] = [
  {
    id: 'card.captain_marrow',
    name: 'Captain Marrow',
    cardClass: 'hero',
    rarity: 'epic',
    attackType: 'melee',
    element: 'dark',
    baseStats: { strength: 720, attack: 84, speed: 12 },
    growth: 'growth.epic',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.rally_cry', unlockStars: 1 },
      { skillId: 'skill.bulwark_call', unlockStars: 2 },
      { skillId: 'skill.riptide_slash', unlockStars: 3 },
      { skillId: 'skill.guard_stance', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    leaderSkill: {
      description: 'Buffs all other Melee allies by 12% Strength.',
      target: { side: 'ally', scope: 'all', where: { attackType: 'melee' } },
      stat: 'strength',
      percent: 12,
    },
    artKey: 'card.captain_marrow',
    lore: 'Lost the ship. Kept the crew.',
    enemyOnly: false,
  },
  {
    id: 'card.oracle_vess',
    name: 'Oracle Vess',
    cardClass: 'hero',
    rarity: 'epic',
    attackType: 'ranged',
    element: 'ice',
    baseStats: { strength: 540, attack: 96, speed: 14 },
    growth: 'growth.epic',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.mend_spore', unlockStars: 1 },
      { skillId: 'skill.frost_lance', unlockStars: 2 },
      { skillId: 'skill.chill_wind', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    leaderSkill: {
      description: 'Buffs all other Ranged allies by 10% Attack.',
      target: { side: 'ally', scope: 'all', where: { attackType: 'ranged' } },
      stat: 'attack',
      percent: 10,
    },
    artKey: 'card.oracle_vess',
    lore: 'Reads the tide the way others read a page.',
    enemyOnly: false,
  },
  {
    id: 'card.warden_ashvale',
    name: 'Warden Ashvale',
    cardClass: 'hero',
    rarity: 'legendary',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 1040, attack: 126, speed: 13 },
    growth: 'growth.legendary',
    attackPattern: 'pattern.cross',
    skills: [
      { skillId: 'skill.riptide_slash', unlockStars: 1 },
      { skillId: 'skill.cinder_volley', unlockStars: 2 },
      { skillId: 'skill.bulwark_call', unlockStars: 3 },
      { skillId: 'skill.rally_cry', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    leaderSkill: {
      description: 'Buffs all other allies by 8% Attack.',
      target: { side: 'ally', scope: 'all' },
      stat: 'attack',
      percent: 8,
    },
    artKey: 'card.warden_ashvale',
    lore: 'Held the last bridge alone, and is still holding it.',
    enemyOnly: false,
  },

  // --- Phase 7 ---------------------------------------------------------------
  {
    id: 'card.serjeant_pike',
    name: 'Serjeant Pike',
    cardClass: 'hero',
    rarity: 'rare',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 620, attack: 74, speed: 11 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.iron_vow', unlockStars: 1 },
      { skillId: 'skill.rally_cry', unlockStars: 2 },
      { skillId: 'skill.stone_skin', unlockStars: 3 },
      { skillId: 'skill.guard_stance', unlockStars: 4 },
      { skillId: 'skill.second_wind', unlockStars: 5 },
    ],
    leaderSkill: {
      description: 'Buffs all other allies by 8% Strength.',
      target: { side: 'ally', scope: 'all' },
      stat: 'strength',
      percent: 8,
    },
    artKey: 'card.serjeant_pike',
    lore: 'Never promoted. Never needed to be.',
    enemyOnly: false,
  },
  {
    id: 'card.lumen_arc',
    name: 'Lumen Arc',
    cardClass: 'hero',
    rarity: 'epic',
    attackType: 'ranged',
    element: 'lightning',
    baseStats: { strength: 560, attack: 104, speed: 16 },
    growth: 'growth.epic',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.static_field', unlockStars: 1 },
      { skillId: 'skill.thunder_clap', unlockStars: 2 },
      { skillId: 'skill.gale_step', unlockStars: 3 },
      { skillId: 'skill.last_light', unlockStars: 4 },
      { skillId: 'skill.warding_hymn', unlockStars: 5 },
    ],
    leaderSkill: {
      description: 'Buffs all other Ranged allies by 14% Attack.',
      target: { side: 'ally', scope: 'all', where: { attackType: 'ranged' } },
      stat: 'attack',
      percent: 14,
    },
    artKey: 'card.lumen_arc',
    lore: 'Speaks in the pause before the thunder.',
    enemyOnly: false,
  },
  {
    id: 'card.hollow_queen',
    name: 'The Hollow Queen',
    cardClass: 'hero',
    rarity: 'legendary',
    attackType: 'ranged',
    element: 'dark',
    baseStats: { strength: 980, attack: 130, speed: 13 },
    growth: 'growth.legendary',
    attackPattern: 'pattern.column',
    skills: [
      { skillId: 'skill.hollow_grasp', unlockStars: 1 },
      { skillId: 'skill.blight_bloom', unlockStars: 2 },
      { skillId: 'skill.last_light', unlockStars: 3 },
      { skillId: 'skill.avalanche', unlockStars: 4 },
      { skillId: 'skill.warding_hymn', unlockStars: 5 },
    ],
    leaderSkill: {
      description: 'Buffs all other allies by 11% Attack.',
      target: { side: 'ally', scope: 'all' },
      stat: 'attack',
      percent: 11,
    },
    artKey: 'card.hollow_queen',
    lore: 'The crown was hers before the kingdom was empty.',
    enemyOnly: false,
  },
];

/** Enemy-only cards. The registry refuses to put these in summon pools. */
const ENEMIES: readonly CardDef[] = [
  {
    id: 'card.gloom_rat',
    name: 'Gloom Rat',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'melee',
    element: 'dark',
    baseStats: { strength: 260, attack: 40, speed: 12 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [],
    artKey: 'card.gloom_rat',
    enemyOnly: true,
  },
  {
    id: 'card.gloom_bat',
    name: 'Gloom Bat',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'ranged',
    element: 'dark',
    baseStats: { strength: 200, attack: 48, speed: 15 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [],
    artKey: 'card.gloom_bat',
    enemyOnly: true,
  },
  {
    id: 'card.brine_crab',
    name: 'Brine Crab',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'melee',
    element: 'ice',
    baseStats: { strength: 430, attack: 44, speed: 6 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.guard_stance', unlockStars: 1 },
      { skillId: 'skill.bulwark_call', unlockStars: 2 },
    ],
    artKey: 'card.brine_crab',
    enemyOnly: true,
  },
  {
    id: 'card.reef_stalker',
    name: 'Reef Stalker',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'ranged',
    element: 'nature',
    baseStats: { strength: 250, attack: 62, speed: 13 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.venom_bite', unlockStars: 1 },
      { skillId: 'skill.spore_burst', unlockStars: 2 },
    ],
    artKey: 'card.reef_stalker',
    enemyOnly: true,
  },
  {
    id: 'card.tide_wraith',
    name: 'Tide Wraith',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'ranged',
    element: 'ice',
    baseStats: { strength: 330, attack: 76, speed: 12 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.frost_lance', unlockStars: 1 },
      { skillId: 'skill.chill_wind', unlockStars: 2 },
    ],
    artKey: 'card.tide_wraith',
    enemyOnly: true,
  },
  {
    id: 'card.coral_brute',
    name: 'Coral Brute',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 620, attack: 70, speed: 8 },
    growth: 'growth.rare',
    attackPattern: 'pattern.splash',
    skills: [],
    artKey: 'card.coral_brute',
    enemyOnly: true,
  },
  {
    id: 'card.salt_shaman',
    name: 'Salt Shaman',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'ranged',
    element: 'lightning',
    baseStats: { strength: 340, attack: 68, speed: 11 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.mend_spore', unlockStars: 1 },
      { skillId: 'skill.rally_cry', unlockStars: 2 },
    ],
    artKey: 'card.salt_shaman',
    enemyOnly: true,
  },
  {
    id: 'card.deep_maw',
    name: 'Deep Maw',
    cardClass: 'unit',
    rarity: 'epic',
    attackType: 'melee',
    element: 'dark',
    baseStats: { strength: 780, attack: 86, speed: 9 },
    growth: 'growth.epic',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.venom_bite', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
    ],
    artKey: 'card.deep_maw',
    enemyOnly: true,
  },
  {
    id: 'card.tide_tyrant',
    name: 'Tide Tyrant',
    cardClass: 'unit',
    rarity: 'legendary',
    attackType: 'melee',
    element: 'ice',
    baseStats: { strength: 1900, attack: 104, speed: 10 },
    growth: 'growth.legendary',
    attackPattern: 'pattern.row',
    skills: [
      { skillId: 'skill.tide_surge', unlockStars: 1 },
      { skillId: 'skill.riptide_slash', unlockStars: 2 },
      { skillId: 'skill.chill_wind', unlockStars: 3 },
    ],
    artKey: 'card.tide_tyrant',
    lore: 'The isles were quiet before it woke.',
    enemyOnly: true,
  },

  // --- Ashfall Reach (fire) --------------------------------------------------
  {
    id: 'card.cinder_imp',
    name: 'Cinder Imp',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 290, attack: 46, speed: 14 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [],
    artKey: 'card.cinder_imp',
    enemyOnly: true,
  },
  {
    id: 'card.ash_crawler',
    name: 'Ash Crawler',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'ranged',
    element: 'fire',
    baseStats: { strength: 225, attack: 55, speed: 11 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [],
    artKey: 'card.ash_crawler',
    enemyOnly: true,
  },
  {
    id: 'card.magma_brute',
    name: 'Magma Brute',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 520, attack: 58, speed: 5 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.single',
    skills: [{ skillId: 'skill.guard_stance', unlockStars: 1 }],
    artKey: 'card.magma_brute',
    enemyOnly: true,
  },
  {
    id: 'card.pyre_shade',
    name: 'Pyre Shade',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'ranged',
    element: 'fire',
    baseStats: { strength: 310, attack: 84, speed: 16 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.cinder_volley', unlockStars: 1 },
      { skillId: 'skill.spore_burst', unlockStars: 2 },
    ],
    artKey: 'card.pyre_shade',
    enemyOnly: true,
  },
  {
    id: 'card.forge_golem',
    name: 'Forge Golem',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 700, attack: 70, speed: 4 },
    growth: 'growth.rare',
    attackPattern: 'pattern.splash',
    skills: [{ skillId: 'skill.bulwark_call', unlockStars: 1 }],
    artKey: 'card.forge_golem',
    enemyOnly: true,
  },
  {
    id: 'card.ash_reaver',
    name: 'Ash Reaver',
    cardClass: 'unit',
    rarity: 'epic',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 760, attack: 108, speed: 15 },
    growth: 'growth.epic',
    attackPattern: 'pattern.row',
    skills: [
      { skillId: 'skill.riptide_slash', unlockStars: 1 },
      { skillId: 'skill.rally_cry', unlockStars: 2 },
    ],
    artKey: 'card.ash_reaver',
    lore: 'It walks the cooling crust and leaves nothing standing behind it.',
    enemyOnly: true,
  },
  {
    id: 'card.emberlord_vashk',
    name: 'Emberlord Vashk',
    cardClass: 'unit',
    rarity: 'legendary',
    attackType: 'melee',
    element: 'fire',
    baseStats: { strength: 1500, attack: 138, speed: 12 },
    growth: 'growth.legendary',
    attackPattern: 'pattern.cross',
    skills: [
      { skillId: 'skill.cinder_volley', unlockStars: 1 },
      { skillId: 'skill.thunder_clap', unlockStars: 2 },
      { skillId: 'skill.rally_cry', unlockStars: 3 },
    ],
    artKey: 'card.emberlord_vashk',
    lore: 'The mountain did not erupt. It answered him.',
    enemyOnly: true,
  },

  // --- Verdant Wound (nature) ------------------------------------------------
  {
    id: 'card.thorn_hound',
    name: 'Thorn Hound',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 330, attack: 52, speed: 17 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [],
    artKey: 'card.thorn_hound',
    enemyOnly: true,
  },
  {
    id: 'card.spore_drifter',
    name: 'Spore Drifter',
    cardClass: 'unit',
    rarity: 'common',
    attackType: 'ranged',
    element: 'nature',
    baseStats: { strength: 265, attack: 60, speed: 10 },
    growth: 'growth.common',
    attackPattern: 'pattern.single',
    skills: [{ skillId: 'skill.venom_bite', unlockStars: 1 }],
    artKey: 'card.spore_drifter',
    enemyOnly: true,
  },
  {
    id: 'card.bramble_ogre',
    name: 'Bramble Ogre',
    cardClass: 'unit',
    rarity: 'uncommon',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 640, attack: 66, speed: 6 },
    growth: 'growth.uncommon',
    attackPattern: 'pattern.splash',
    skills: [{ skillId: 'skill.guard_stance', unlockStars: 1 }],
    artKey: 'card.bramble_ogre',
    enemyOnly: true,
  },
  {
    id: 'card.moss_shaman',
    name: 'Moss Shaman',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'ranged',
    element: 'nature',
    baseStats: { strength: 380, attack: 78, speed: 13 },
    growth: 'growth.rare',
    attackPattern: 'pattern.single',
    skills: [
      { skillId: 'skill.mend_spore', unlockStars: 1 },
      { skillId: 'skill.spore_burst', unlockStars: 2 },
    ],
    artKey: 'card.moss_shaman',
    enemyOnly: true,
  },
  {
    id: 'card.vine_horror',
    name: 'Vine Horror',
    cardClass: 'unit',
    rarity: 'rare',
    attackType: 'melee',
    element: 'nature',
    baseStats: { strength: 820, attack: 82, speed: 8 },
    growth: 'growth.rare',
    attackPattern: 'pattern.column',
    skills: [{ skillId: 'skill.venom_bite', unlockStars: 1 }],
    artKey: 'card.vine_horror',
    enemyOnly: true,
  },
  {
    id: 'card.blightfang',
    name: 'Blightfang',
    cardClass: 'unit',
    rarity: 'epic',
    attackType: 'ranged',
    element: 'nature',
    baseStats: { strength: 700, attack: 126, speed: 18 },
    growth: 'growth.epic',
    attackPattern: 'pattern.column',
    skills: [
      { skillId: 'skill.spore_burst', unlockStars: 1 },
      { skillId: 'skill.venom_bite', unlockStars: 2 },
    ],
    artKey: 'card.blightfang',
    lore: 'Everything it bites keeps growing, in the wrong direction.',
    enemyOnly: true,
  },
  {
    id: 'card.rootmother_yal',
    name: 'Rootmother Yal',
    cardClass: 'unit',
    rarity: 'legendary',
    attackType: 'ranged',
    element: 'nature',
    baseStats: { strength: 1720, attack: 130, speed: 9 },
    growth: 'growth.legendary',
    attackPattern: 'pattern.row',
    skills: [
      { skillId: 'skill.spore_burst', unlockStars: 1 },
      { skillId: 'skill.mend_spore', unlockStars: 2 },
      { skillId: 'skill.thunder_clap', unlockStars: 3 },
    ],
    artKey: 'card.rootmother_yal',
    lore: 'The wound in the forest is not a wound. It is a mouth.',
    enemyOnly: true,
  },
];

export const CARD_DEFS: readonly CardDef[] = [...PLAYER_UNITS, ...PLAYER_HEROES, ...ENEMIES];

/** The deck the player starts with — a hero plus a workable spread of roles. */
export const STARTER_CARD_IDS: readonly string[] = [
  'card.captain_marrow',
  'card.ember_drake',
  'card.stone_sentry',
  'card.thorn_sprout',
  'card.gale_archer',
  'card.frost_imp',
  'card.spark_wisp',
];
